server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8090
  servlet:
    context-path: /emos-api
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.220.15.121:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: Zhonghua@456
      initial-size: 2
      max-active: 4
      min-idle: 4
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: 124.220.15.121
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: 124.220.15.121
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: 123456
      
sa-token:
  #token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  #关闭读取Cookie中Token
  isReadCookie: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on
tencent:
  cloud:
    appId: 1313613702
    secretId: AKIDU7ZrxpX0HKEyX2OYVHsEQTM1VmPq2BB1
    secretKey: hAQcgV7Zu39KPPK4eLsGVYTGqifaIwSp
    region: ap-shanghai
    bucket: emos-1313613702
  trtc:
    appId: 1400804592
    secretKey: 353233a80c491a553b84b05866fabb5e654d2a69c4fd8cc326f9ab7dc2ad364d
    expire: 86400
wx:
  app-id: wx99546af32003af51
  app-secret: 9f05a298cd9cf0306350c044f4ccb53d

emos:
  code: code
  tcode: tcode
  receiveNotify: http://localhost:8090/emos-api/meeting/recieveNotify

workflow:
  url: http://localhost:9090/emos-workflow